theme = 'hextra'
enableEmoji = true

[[menu.main]]
name = "News"
pageRef = "/blog"
weight = 1

[[menu.main]]
name = "Docs"
pageRef = "/docs"
weight = 2

[[menu.main]]
name = "Gabonomicon"
pageRef = "/docs/gabonomicon"
weight = 3

[[menu.main]]
name = "Search"
weight = 4

[menu.main.params]
type = "search"

[[menu.main]]
name = "GitHub"
weight = 5
url = "https://github.com/gab-language/cgab"

[[menu.main]]
name = "Install"
pageRef = "/docs/installation"
weight = 6

[params.page.contextMenu]
enable = true

[params.theme]
displayToggle = false

[params.footer]
displayPoweredBy = false
title = "gab"
copyright = "© 2026 Teddy Randby | All rights reserved"
github = "https://github.com/gab-language/cgab"

[languages.en]
languageName = "English"
weight = 1
title = "gab"

[params.navbar]
displayTitle = true
displayLogo = false
width = "wide"
